---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present
  become: yes

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: yes

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ filebeat_major_version }}.x/apt stable main'
    state: present
    update_cache: yes
  become: yes
